APPL_COBJS += \
          analysis.o \
          basic_travel.o \
          blocksort.o \
          calibration.o \
          color_convers.o \
          dijsktra.o \
          gray_search.o \
          input_code.o \
          mode_select.o \
          motor_encode.o \
          n_calibration.o \
          n_light_sensor.o \
          n_pid.o \
          n_linetracer.o \
          operate_course.o \
          query_degree.o \
          search_root.o \
          pid_value.o \
          starter.o \
          test_get_pid.o 
